name: "DOCUMENTATION"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:

  build_and_deploy:

    runs-on: ${{ matrix.os }}
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Latex
      run: |
        sudo apt install texlive-latex-extra
        sudo apt install dvipng
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        python -m pip install --progress-bar off .
        python -m pip install git+https://github.com/AGrigis/pysphinxdoc.git
    - name: Declare plugins
      run: |
        declare -a plugins=("surfify")
        mkdir ./plugins
        for name in "${plugins[@]}"
        do
            git clone https://github.com/neurospin-deepinsight/$name ./plugins/$name
            ls ./plugins/$name
            ln -s $PWD/plugins/$name/examples $PWD/examples/$name
            ls -l ./examples
            ls ./examples/$name
            python -m pip install git+https://github.com/neurospin-deepinsight/$name
            PLUGPATH=$(python3 -c "import $name; import os; print(os.path.dirname($name.__file__))")
            echo $PLUGPATH
            ln -s $PLUGPATH .
        done
    - name: Compute documentation
      run: |
        mkdir -p tmp/doc
        sphinxdoc -v 2 -p . -n '*nidl' -o tmp/doc
        cd tmp/doc
        make raw-html
        ls source/_static
        ls build/html/_static
        cp -r source/_static/* build/html/_static
        cd ../..
    - name: Upload documentation as an artifact
      uses: actions/upload-artifact@v4
      with: 
        name: html-documentation
        retention-days: 15
        path: |
            tmp/doc/build/html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: tmp/doc/build/html

  build:

    runs-on: ${{ matrix.os }}
    if: ${{ github.ref != 'refs/heads/main' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Latex
      run: |
        sudo apt install texlive-latex-extra
        sudo apt install dvipng
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install joblib
        python -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        python -m pip install --progress-bar off .
        python -m pip install git+https://github.com/AGrigis/pysphinxdoc.git
    - name: Declare plugins
      run: |
        declare -a plugins=("surfify")
        mkdir ./plugins
        for name in "${plugins[@]}"
        do
            git clone https://github.com/neurospin-deepinsight/$name ./plugins/$name
            ln -s $PWD/plugins/$name/examples $PWD/examples/$name
            python -m pip install git+https://github.com/neurospin-deepinsight/$name
            PLUGPATH=$(python3 -c "import $name; import os; print(os.path.dirname($name.__file__))")
            echo $PLUGPATH
            ln -s $PLUGPATH .
        done
    - name: Compute documentation
      run: |
        mkdir -p tmp/doc
        sphinxdoc -v 2 -p . -n '*nidl' -o tmp/doc
        cd tmp/doc
        make raw-html
        ls source/_static
        ls build/html/_static
        cp -r source/_static/* build/html/_static
        cd ../..
